### ISSUE TITLE
unsupported pg version in `~/.pgrx/config.toml` isn't handled

### ISSUE THREAD

**Issue by workingjubilee** [pgcentralfoundation/pgrx#1421]
We never actually remove an old version like pg11 from the config.toml, and it's not clear we should. We can tell the user they need to intervene, but we probably should correctly identify when they must. Currently `PG_VERSION=all cargo pgrx test` doesn't work for my local installation.

Sample busted toml:

```toml
[configs]
pg16 = "/home/jubilee/.pgrx/16.0/pgrx-install/bin/pg_config"
pg13 = "/home/jubilee/.pgrx/13.12/pgrx-install/bin/pg_config"
pg12 = "/home/jubilee/.pgrx/12.16/pgrx-install/bin/pg_config"
pg11 = "/home/jubilee/.pgrx/11.21/pgrx-install/bin/pg_config"
pg14 = "/home/jubilee/.pgrx/14.9/pgrx-install/bin/pg_config"
pg15 = "/home/jubilee/.pgrx/15.4/pgrx-install/bin/pg_config"
```
