### ISSUE TITLE
PG18 Support

### ISSUE THREAD

**Issue by anth0nyleung** [pgcentralfoundation/pgrx#2052]
Hello. The first pg18 beta version is going to be release in about 3 weeks. I could not find any issues tracking the support for Pg18, hence creating a new issue to track this. 

I am curious about whether there's any timeline on supporting that or would it be possible to start on that with the current 18_devel branch.

Thank you.

**Comment by YohDeadfall** [comment]
I plan to work on that, but there's a rule about supporting only final versions. Therefore, it won't be merged till the last moment.

**Comment by anth0nyleung** [comment]
Thanks @YohDeadfall ! Im curious where this rule is defined and the reason behind it. Could you also please clarify on what you mean by final version? do you mean the first beta version / rc / .0 version?

**Comment by YohDeadfall** [comment]
The 18.0 version. See https://github.com/paradedb/paradedb/issues/1019#issuecomment-2836716401.

**Comment by VoVAllen** [comment]
Hi, we have a branch to support PG18 and already tested it with our pgrx extension. Check it at https://github.com/silver-ymz/pgrx/tree/support-18-devel cc @silver-ymz

**Comment by YohDeadfall** [comment]
Oh, that's cool! Could you please open a pull request then?

**Comment by silver-ymz** [comment]
> Could you please open a pull request then?

Yes, I'd like to open a PR then.

**Comment by jakob** [comment]
Sorry for asking stupid questions, but does that mean that we have to wait until PostgreSQL 18 is released in autumn before we can build extensions with pgrx for it?

I'm unfamiliar with Rust / crago / pgrx, I just want to build extensions for PostgreSQL 18beta1 for testing, so that we can release it simultaneously with PostgreSQL 18.

The following commands fail (I assume that is because PostgreSQL 18 is not supported yet)

```sh
cargo install cargo-pgrx # as far as I can tell this installs pgrx 14.3
cargo pgrx init --pg18 # suggests using the argument --pg17 instead :)
```

As I said before, I'm unfamiliar how rust, cargo and pgrx work together, I'm just trying to understand if I can test building extensions for PostgreSQL 18 ahead of time, or if I need to wait until after it was released.

**Comment by usamoi** [comment]
@jakob It's supported in `develop` branch. Use `cargo-pgrx` and `pgrx` in this repo.

**Comment by jakob** [comment]
> Use cargo-pgrx and pgrx in this repo

How do I do this? The readme says something about using `cargo-local-install`, is that what I need to use? Again, apologies for asking stupid questions, I'm so unfamiliar with Rust and cargo I feel like I'm in a foreign country and everyone is speaking a foreign language.

**Comment by usamoi** [comment]
> > Use cargo-pgrx and pgrx in this repo
> 
> How do I do this? The readme says something about using `cargo-local-install`, is that what I need to use? Again, apologies for asking stupid questions, I'm so unfamiliar with Rust and cargo I feel like I'm in a foreign country and everyone is speaking a foreign language.

1. run `cargo install cargo-pgrx --git https://github.com/pgcentralfoundation/pgrx.git --branch develop` to install `cargo-pgrx`
2. edit `Cargo.toml` of your extension from

```toml
[features]
default = ["pg13"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16" ]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17" ]
pg_test = []
```

to

```toml
[features]
default = ["pg13"]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16" ]
pg17 = ["pgrx/pg17", "pgrx-tests/pg17" ]
pg18 = ["pgrx/pg18", "pgrx-tests/pg18" ]
pg_test = []
```

and from

```toml
[dependencies]
pgrx = "=0.14.3"

[dev-dependencies]
pgrx-tests = "=0.14.3"
```

to

```toml
[dependencies]
pgrx = { git = "https://github.com/pgcentralfoundation/pgrx.git" }

[dev-dependencies]
pgrx-tests = { git = "https://github.com/pgcentralfoundation/pgrx.git" }
```

3. build the extension, like original steps

If you encounter any issues, just copy and paste the instructions along with what you see to the AI. It should be able to handle it.
